#!/bin/sh
# Installs the tools this course's labs use, at the versions of the LearnSome.tech lab sandbox, on x86-64
# Ubuntu: the dev container (Dockerfile) and CI (.github/workflows/check.yml) both run it, as root.
# `install-tools.sh ci` leaves out the Linux userland the labs call, which CI does not need.
# Generated by the LearnSome.tech platform (scripts/labs-repos); do not edit here.
set -eu
if [ "$(uname -m)" != x86_64 ]; then
  echo "install-tools.sh: x86-64 Linux only (Codespaces, GitHub Actions); elsewhere install the tools yourself" >&2
  exit 1
fi
mode=${1:-full}
here=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
fetch() { curl -fsSL --retry 3 "$1" -o "$2" && echo "$3  $2" | sha256sum -c - >/dev/null; }

export DEBIAN_FRONTEND=noninteractive
apt-get -o Acquire::Retries=5 -o Acquire::http::Timeout=30 -o Acquire::https::Timeout=30 update -q
apt-get install -y -q --no-install-recommends bash git unzip xz-utils ca-certificates curl
if [ "$mode" != ci ]; then
  apt-get install -y -q --no-install-recommends procps iproute2 util-linux findutils coreutils psmisc lsof strace less tree bc xxd binutils file acl gettext-base netcat-openbsd dnsutils iputils-ping traceroute net-tools openssh-client make patch bsdextrautils shellcheck
  # The sandbox's git is Ubuntu's; the base image puts a newer build first on PATH.
  if [ -x /usr/local/bin/git ] && [ -x /usr/bin/git ]; then ln -sf /usr/bin/git /usr/local/bin/git; fi
fi
rm -rf /var/lib/apt/lists/*
mkdir -p /opt/lab

# Python 3.14.7
fetch 'https://github.com/astral-sh/python-build-standalone/releases/download/20260924/cpython-3.14.7%2B20260924-x86_64-unknown-linux-gnu-install_only_stripped.tar.gz' "$tmp/python.tgz" bd0d0568ccded07bbf1c87727230dc5dd0187e706a87da23c4de78388a229b78
mkdir -p /opt/python && tar -xzf "$tmp/python.tgz" -C /opt/python --strip-components=1
ln -sf /opt/python/bin/python3.14 /usr/local/bin/python3
ln -sf /opt/python/bin/python3.14 /usr/local/bin/python

# ansible-core and yamllint in their own environment (hash-pinned, as in the sandbox)
/opt/python/bin/python3.14 -m venv /opt/pytools
/opt/pytools/bin/pip install -q --no-cache-dir --disable-pip-version-check --require-hashes --only-binary=:all: -r "$here/requirements.txt"
install -m 0755 "$here/ansible-tool" /opt/lab/ansible-tool
for t in ansible ansible-playbook ansible-inventory ansible-config ansible-doc ansible-galaxy ansible-vault ansible-console ansible-pull; do
  ln -sf /opt/lab/ansible-tool "/usr/local/bin/$t"
done
ln -sf /opt/pytools/bin/yamllint /usr/local/bin/yamllint

# OpenSSL 3.5 and curl 8 in their own prefixes, built as the sandbox builds them; ./check puts them first on
# PATH only for the labs that use them. Not needed in CI, which runs no lab programs.
if [ "$mode" != ci ]; then
  apt-get -o Acquire::Retries=5 update -q
  apt-get install -y -q --no-install-recommends build-essential perl xz-utils
  rm -rf /var/lib/apt/lists/*
  fetch 'https://github.com/openssl/openssl/releases/download/openssl-3.5.9/openssl-3.5.9.tar.gz' "$tmp/openssl.tgz" 603f5602e2eef00d77fbd429d34dcd5822bb301757a1bc9cdb24c670f1eb859a
  fetch 'https://curl.se/download/curl-8.22.0.tar.xz' "$tmp/curl.txz" f7ef3ae8a22e521f289803fe93543eb64c329b58aa73a9e224dfd915a2a5f4f7
  mkdir "$tmp/openssl" "$tmp/curl"
  tar -xzf "$tmp/openssl.tgz" -C "$tmp/openssl" --strip-components=1
  tar -xJf "$tmp/curl.txz" -C "$tmp/curl" --strip-components=1
  (cd "$tmp/openssl" && ./Configure --prefix=/opt/openssl-3.5 --openssldir=/opt/openssl-3.5/ssl --libdir=lib shared no-docs no-tests '-Wl,-rpath,/opt/openssl-3.5/lib' >/dev/null && make -j"$(nproc)" >/dev/null && make install_sw install_ssldirs >/dev/null)
  (cd "$tmp/curl" && ./configure --prefix=/opt/curl-8 --with-openssl=/opt/openssl-3.5 --disable-static --disable-ldap --disable-ldaps --disable-manual --disable-docs --without-libpsl --without-brotli --without-zstd --without-nghttp2 --without-libidn2 --without-zlib LDFLAGS='-Wl,-rpath,/opt/openssl-3.5/lib -Wl,-rpath,/opt/curl-8/lib' >/dev/null && make -j"$(nproc)" >/dev/null && make install >/dev/null)
  /opt/openssl-3.5/bin/openssl version
fi

# The toolchains also under /opt/lab/bin, the sandbox's own PATH entry
mkdir -p /opt/lab/bin
ln -sf /opt/python/bin/python3.14 /opt/lab/bin/python3
ln -sf /opt/python/bin/python3.14 /opt/lab/bin/python
